// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nnpb_routes.proto

package nnpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinClusterResponse_JoinStatus int32

const (
	JoinClusterResponse_SUCCESS JoinClusterResponse_JoinStatus = 0
	JoinClusterResponse_FAILURE JoinClusterResponse_JoinStatus = 1
)

var JoinClusterResponse_JoinStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var JoinClusterResponse_JoinStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x JoinClusterResponse_JoinStatus) String() string {
	return proto.EnumName(JoinClusterResponse_JoinStatus_name, int32(x))
}

func (JoinClusterResponse_JoinStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38481b258f86a690, []int{1, 0}
}

type JoinClusterRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,json=iP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=Port,json=port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterRequest) Reset()         { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()    {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38481b258f86a690, []int{0}
}

func (m *JoinClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterRequest.Unmarshal(m, b)
}
func (m *JoinClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterRequest.Marshal(b, m, deterministic)
}
func (m *JoinClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterRequest.Merge(m, src)
}
func (m *JoinClusterRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClusterRequest.Size(m)
}
func (m *JoinClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterRequest proto.InternalMessageInfo

func (m *JoinClusterRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *JoinClusterRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *JoinClusterRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type JoinClusterResponse struct {
	Status               JoinClusterResponse_JoinStatus `protobuf:"varint,1,opt,name=Status,json=status,proto3,enum=nnpb.JoinClusterResponse_JoinStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *JoinClusterResponse) Reset()         { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()    {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38481b258f86a690, []int{1}
}

func (m *JoinClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterResponse.Unmarshal(m, b)
}
func (m *JoinClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterResponse.Marshal(b, m, deterministic)
}
func (m *JoinClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterResponse.Merge(m, src)
}
func (m *JoinClusterResponse) XXX_Size() int {
	return xxx_messageInfo_JoinClusterResponse.Size(m)
}
func (m *JoinClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterResponse proto.InternalMessageInfo

func (m *JoinClusterResponse) GetStatus() JoinClusterResponse_JoinStatus {
	if m != nil {
		return m.Status
	}
	return JoinClusterResponse_SUCCESS
}

func init() {
	proto.RegisterEnum("nnpb.JoinClusterResponse_JoinStatus", JoinClusterResponse_JoinStatus_name, JoinClusterResponse_JoinStatus_value)
	proto.RegisterType((*JoinClusterRequest)(nil), "nnpb.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "nnpb.JoinClusterResponse")
}

func init() {
	proto.RegisterFile("nnpb_routes.proto", fileDescriptor_38481b258f86a690)
}

var fileDescriptor_38481b258f86a690 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcb, 0x2b, 0x48,
	0x8a, 0x2f, 0xca, 0x2f, 0x2d, 0x49, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01,
	0x09, 0x29, 0x79, 0x70, 0x09, 0x79, 0xe5, 0x67, 0xe6, 0x39, 0xe7, 0x94, 0x16, 0x97, 0xa4, 0x16,
	0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xba, 0x80, 0xf9, 0x01, 0x12, 0x4c, 0x50, 0x7e, 0x80, 0x90,
	0x10, 0x17, 0x4b, 0x40, 0x7e, 0x51, 0x89, 0x04, 0x33, 0x58, 0x84, 0xa5, 0x20, 0xbf, 0xa8, 0x44,
	0xa9, 0x9a, 0x4b, 0x18, 0xc5, 0xa4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x1b, 0x2e, 0xb6,
	0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0xb0, 0x71, 0x7c, 0x46, 0x2a, 0x7a, 0x20, 0x7b, 0xf5, 0xb0,
	0x28, 0x05, 0x8b, 0x41, 0xd4, 0x06, 0xb1, 0x15, 0x83, 0x69, 0x25, 0x35, 0x2e, 0x2e, 0x84, 0xa8,
	0x10, 0x37, 0x17, 0x7b, 0x70, 0xa8, 0xb3, 0xb3, 0x6b, 0x70, 0xb0, 0x00, 0x03, 0x88, 0xe3, 0xe6,
	0xe8, 0xe9, 0x13, 0x1a, 0xe4, 0x2a, 0xc0, 0x68, 0x14, 0xc3, 0x25, 0xe6, 0x97, 0x98, 0x9b, 0xea,
	0x97, 0x9f, 0x92, 0xea, 0x99, 0x57, 0x92, 0x5a, 0x94, 0x97, 0x98, 0x13, 0x04, 0xf6, 0xac, 0x90,
	0x13, 0x17, 0x37, 0x92, 0x5d, 0x42, 0x12, 0x58, 0xac, 0x07, 0xfb, 0x59, 0x4a, 0x12, 0xa7, 0xc3,
	0x92, 0xd8, 0xc0, 0x21, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x42, 0x2f, 0xe8, 0x46,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NameNodeInternalRoutesClient is the client API for NameNodeInternalRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NameNodeInternalRoutesClient interface {
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
}

type nameNodeInternalRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewNameNodeInternalRoutesClient(cc grpc.ClientConnInterface) NameNodeInternalRoutesClient {
	return &nameNodeInternalRoutesClient{cc}
}

func (c *nameNodeInternalRoutesClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, "/nnpb.NameNodeInternalRoutes/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameNodeInternalRoutesServer is the server API for NameNodeInternalRoutes service.
type NameNodeInternalRoutesServer interface {
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
}

// UnimplementedNameNodeInternalRoutesServer can be embedded to have forward compatible implementations.
type UnimplementedNameNodeInternalRoutesServer struct {
}

func (*UnimplementedNameNodeInternalRoutesServer) JoinCluster(ctx context.Context, req *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}

func RegisterNameNodeInternalRoutesServer(s *grpc.Server, srv NameNodeInternalRoutesServer) {
	s.RegisterService(&_NameNodeInternalRoutes_serviceDesc, srv)
}

func _NameNodeInternalRoutes_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameNodeInternalRoutesServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nnpb.NameNodeInternalRoutes/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameNodeInternalRoutesServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NameNodeInternalRoutes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nnpb.NameNodeInternalRoutes",
	HandlerType: (*NameNodeInternalRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCluster",
			Handler:    _NameNodeInternalRoutes_JoinCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nnpb_routes.proto",
}
