// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routes.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinClusterResponse_JoinStatus int32

const (
	JoinClusterResponse_SUCCESS JoinClusterResponse_JoinStatus = 0
	JoinClusterResponse_FAILURE JoinClusterResponse_JoinStatus = 1
)

var JoinClusterResponse_JoinStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var JoinClusterResponse_JoinStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x JoinClusterResponse_JoinStatus) String() string {
	return proto.EnumName(JoinClusterResponse_JoinStatus_name, int32(x))
}

func (JoinClusterResponse_JoinStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_078f480fb67d0ab3, []int{1, 0}
}

type JoinClusterRequest struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,json=iP,proto3" json:"IP,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port,json=port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinClusterRequest) Reset()         { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()    {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_078f480fb67d0ab3, []int{0}
}

func (m *JoinClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterRequest.Unmarshal(m, b)
}
func (m *JoinClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterRequest.Marshal(b, m, deterministic)
}
func (m *JoinClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterRequest.Merge(m, src)
}
func (m *JoinClusterRequest) XXX_Size() int {
	return xxx_messageInfo_JoinClusterRequest.Size(m)
}
func (m *JoinClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterRequest proto.InternalMessageInfo

func (m *JoinClusterRequest) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *JoinClusterRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type JoinClusterResponse struct {
	Status               JoinClusterResponse_JoinStatus `protobuf:"varint,1,opt,name=Status,json=status,proto3,enum=protobuf.JoinClusterResponse_JoinStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *JoinClusterResponse) Reset()         { *m = JoinClusterResponse{} }
func (m *JoinClusterResponse) String() string { return proto.CompactTextString(m) }
func (*JoinClusterResponse) ProtoMessage()    {}
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_078f480fb67d0ab3, []int{1}
}

func (m *JoinClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinClusterResponse.Unmarshal(m, b)
}
func (m *JoinClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinClusterResponse.Marshal(b, m, deterministic)
}
func (m *JoinClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinClusterResponse.Merge(m, src)
}
func (m *JoinClusterResponse) XXX_Size() int {
	return xxx_messageInfo_JoinClusterResponse.Size(m)
}
func (m *JoinClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinClusterResponse proto.InternalMessageInfo

func (m *JoinClusterResponse) GetStatus() JoinClusterResponse_JoinStatus {
	if m != nil {
		return m.Status
	}
	return JoinClusterResponse_SUCCESS
}

func init() {
	proto.RegisterEnum("protobuf.JoinClusterResponse_JoinStatus", JoinClusterResponse_JoinStatus_name, JoinClusterResponse_JoinStatus_value)
	proto.RegisterType((*JoinClusterRequest)(nil), "protobuf.JoinClusterRequest")
	proto.RegisterType((*JoinClusterResponse)(nil), "protobuf.JoinClusterResponse")
}

func init() {
	proto.RegisterFile("routes.proto", fileDescriptor_078f480fb67d0ab3)
}

var fileDescriptor_078f480fb67d0ab3 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a,
	0x16, 0x5c, 0x42, 0x5e, 0xf9, 0x99, 0x79, 0xce, 0x39, 0xa5, 0xc5, 0x25, 0xa9, 0x45, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x01, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x4c, 0x99, 0x01, 0x42, 0x42, 0x5c, 0x2c, 0x01, 0xf9, 0x45, 0x25, 0x12, 0x4c, 0x60,
	0x11, 0x96, 0x82, 0xfc, 0xa2, 0x12, 0xa5, 0x7a, 0x2e, 0x61, 0x14, 0x9d, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x0e, 0x5c, 0x6c, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x60, 0xed, 0x7c, 0x46,
	0x1a, 0x7a, 0x30, 0xbb, 0xf4, 0xb0, 0x28, 0x07, 0x8b, 0x41, 0xd4, 0x07, 0xb1, 0x15, 0x83, 0x69,
	0x25, 0x35, 0x2e, 0x2e, 0x84, 0xa8, 0x10, 0x37, 0x17, 0x7b, 0x70, 0xa8, 0xb3, 0xb3, 0x6b, 0x70,
	0xb0, 0x00, 0x03, 0x88, 0xe3, 0xe6, 0xe8, 0xe9, 0x13, 0x1a, 0xe4, 0x2a, 0xc0, 0x68, 0x14, 0xc3,
	0xc5, 0xe7, 0x99, 0x57, 0x92, 0x5a, 0x94, 0x97, 0x98, 0x13, 0x04, 0xf6, 0x9c, 0x90, 0x17, 0x17,
	0x37, 0x92, 0x1d, 0x42, 0x32, 0x38, 0xac, 0x06, 0xfb, 0x51, 0x4a, 0x16, 0xaf, 0xc3, 0x92, 0xd8,
	0xc0, 0xb2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x38, 0x5b, 0xd8, 0x39, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InternalRoutesClient is the client API for InternalRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InternalRoutesClient interface {
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
}

type internalRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalRoutesClient(cc grpc.ClientConnInterface) InternalRoutesClient {
	return &internalRoutesClient{cc}
}

func (c *internalRoutesClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, "/protobuf.InternalRoutes/JoinCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalRoutesServer is the server API for InternalRoutes service.
type InternalRoutesServer interface {
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
}

// UnimplementedInternalRoutesServer can be embedded to have forward compatible implementations.
type UnimplementedInternalRoutesServer struct {
}

func (*UnimplementedInternalRoutesServer) JoinCluster(ctx context.Context, req *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinCluster not implemented")
}

func RegisterInternalRoutesServer(s *grpc.Server, srv InternalRoutesServer) {
	s.RegisterService(&_InternalRoutes_serviceDesc, srv)
}

func _InternalRoutes_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalRoutesServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.InternalRoutes/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalRoutesServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalRoutes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.InternalRoutes",
	HandlerType: (*InternalRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinCluster",
			Handler:    _InternalRoutes_JoinCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routes.proto",
}
