name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check Data Node Build
      run: |
        cd data_node/entrypoint && make build

    - name: Check Name Node Build
      run: |
        cd name_node/entrypoint && make build
